[build]
  command = "npm run build"  # or "next build" if you don't have a build script
  publish = ".next"
  functions = "netlify-functions"
  environment = { NEXT_PRIVATE_TARGET = "server" }

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/:splat"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/index.html"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-nextjs"
