# Netlify Configuration File for your project

[build]
  # The directory where the site will be built
  publish = "public"  # If your frontend assets are in the "public" directory, change this to where your frontend code is located
  functions = "netlify-functions"  # Directory where your Netlify functions (serverless functions) will reside

[[plugins]]
  package = "@netlify/plugin-nextjs"  # If you're using Next.js, include this plugin. Otherwise, you can remove this line.

[dev]
  # This is for running the site locally with Netlify CLI
  functions = "netlify-functions"  # Same as above, specify your functions folder

[[redirects]]
  # Redirect all server-side requests to the serverless function
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  # If you're using client-side routing (for single-page apps like React), ensure this route works for all paths
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Optional: Add environment variables (for things like MongoDB URI, etc.)
[env]
  MONGO_URI = "mongodb://localhost/my-demo-website"  # Update this if using MongoDB Atlas
  JWT_SECRET = "b2fe5a9b8d7c506b83e06ebd0d923ef3fd43e27ec7343c0e5c60bc2d5fe1a0cd"  # Update this with your JWT secret for authentication
  PORT = "5001"  # This ensures your app runs on port 5001 if you need to define it in the environment
